apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}-analysis
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "name" . }}-analysis
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-analysis
    spec:
      containers:
        - image: "{{ .Values.backend.analysis.image.repository }}:{{ .Values.backend.analysis.image.tag }}"
          imagePullPolicy: {{ .Values.backend.analysis.image.pullPolicy }}
          name: {{ template "name" . }}-analysis
          ports:
            - containerPort: {{ .Values.backend.analysis.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SERVER_PORT
              value: "{{ .Values.backend.analysis.port }}"
            - name: KRAKEN_GRAFANA_URL
              value: "http://{{ .Values.grafana.fullnameOverride }}:{{ .Values.grafana.service.port }}"
            - name: KRAKEN_INFLUXDB_URL
              value: "http://{{ .Values.influxdb.fullnameOverride }}:{{ .Values.influxdb.config.http.bind_address }}"
            - name: KRAKEN_STORAGE_URL
              value: "http://{{ template "name" . }}-storage:{{ .Values.backend.storage.port }}"
