apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}-static
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "name" . }}-static
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-static
    spec:
      containers:
        - image: "{{ .Values.backend.static.image.repository }}:{{ .Values.backend.static.image.tag }}"
          imagePullPolicy: {{ .Values.backend.static.image.pullPolicy }}
          name: {{ template "name" . }}-static
          ports:
              - containerPort: {{ .Values.backend.static.port }}
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: storage-data
              readOnly: true
      volumes:
        - name: storage-data
          persistentVolumeClaim:
            claimName: storage-data


