---
{{- if .Values.backend.maxUnavailable }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "name" . }}-backend-pdb
  labels:
    app: {{ template "name" . }}-backend-pdb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  maxUnavailable: {{ .Values.backend.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "name" . }}-backend
{{- end }}