---

elasticsearch:
  # Permit co-located instances for solitary minikube virtual machines.
  antiAffinity: "soft"

  # Shrink default JVM heap.
  esJavaOpts: "-Xmx128m -Xms128m"

  # Request smaller persistent volumes.
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "standard"
    resources:
      requests:
        storage: 1Gi

ingress:
  enabled: true
  annotations: {}
  path: /
  hosts:
  - "192.168.99.100.xip.io"

backend:
  env:
    server.hostname: "192.168.99.100.xip.io"